---
	
- src: https://github.com/JaegerP/ansible-nginx_php-fpm.git
  name: php-fpm
	
- src: https://github.com/JaegerP/ansible-mysql_server
  name: mysql-server
	
- src: https://github.com/JaegerP/ansible-nginx_site.git
  name: nginx-site
