---
	
- src: https://github.com/JaegerP/ansible-nginx_php-fpm.git
  name: nginx_php-fpm
	
- src: https://github.com/JaegerP/ansible-mysql_server
  name: mysql_server
	
- src: https://github.com/JaegerP/ansible-nginx_site.git
  name: nginx_site
